# Generated by Django 5.0.6 on 2024-06-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='img_profile',
            field=models.ImageField(null=True, upload_to='uploads/music/image/'),
        ),
    ]
