# Generated by Django 5.0.6 on 2024-05-30 05:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_music_modified_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='music',
            name='img_profile',
            field=models.ImageField(null=True, upload_to='uploads/music/'),
        ),
        migrations.AlterField(
            model_name='music',
            name='music_file',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
