# Generated by Django 5.0.6 on 2024-06-06 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='lyrics',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='music',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='music',
            name='img_profile',
            field=models.ImageField(null=True, upload_to='uploads/music/image/'),
        ),
    ]
