# Generated by Django 5.0.6 on 2024-06-02 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_alter_music_artist_alter_music_img_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='music_file',
            field=models.FileField(null=True, upload_to='uploads/music/'),
        ),
    ]
