# Generated by Django 5.0.6 on 2024-06-08 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_music_lyrics_alter_comment_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='img_cover',
            field=models.ImageField(default='uploads/default/cover.jpeg', null=True, upload_to='uploads/music/cover/'),
        ),
        migrations.AlterField(
            model_name='music',
            name='img_profile',
            field=models.ImageField(default='uploads/default/defaultMusic.jpg', null=True, upload_to='uploads/music/profile/'),
        ),
    ]
