# Generated by Django 5.0.6 on 2024-06-08 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_alter_like_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentlike',
            name='is_like',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='commentreplylike',
            name='is_like',
            field=models.BooleanField(default=True),
        ),
    ]
