# Generated by Django 5.0.6 on 2024-06-08 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_alter_comment_user_alter_commentlike_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='music',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music_comments', to='music.music'),
        ),
        migrations.AlterField(
            model_name='commentlike',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music_comment_likes', to='music.comment'),
        ),
        migrations.AlterField(
            model_name='commentreply',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music_comment_replies', to='music.comment'),
        ),
        migrations.AlterField(
            model_name='commentreplylike',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music_comment_reply_likes', to='music.commentreply'),
        ),
        migrations.AlterField(
            model_name='like',
            name='music',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music_likes', to='music.music'),
        ),
    ]
