# Generated by Django 5.0.6 on 2024-06-09 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0012_alter_comment_music_alter_commentlike_comment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentreplylike',
            old_name='comment',
            new_name='reply',
        ),
    ]
