# Generated by Django 5.0.6 on 2024-06-10 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customizeable', '0002_remove_customtheme_user'),
        ('music', '0014_rename_reply_commentreplylike_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='theme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customizeable.customtheme'),
        ),
    ]
