FROM python:3.10-bookworm AS dev

ARG DJANGO_ENV 

ENV DJANGO_ENV=${DJANGO_ENV} \
  PYTHONFAULTHANDLER=1 \
  PYTHONUNBUFFERED=1 \
  PYTHONHASHSEED=random \
  PIP_NO_CACHE_DIR=off \
  PIP_DISABLE_PIP_VERSION_CHECK=on \
  PIP_DEFAULT_TIMEOUT=100 \
  POETRY_VERSION=1.8.2 \
  POETRY_VIRTUALENVS_CREATE=false \
  POETRY_CACHE_DIR='/var/cache/pypoetry'

RUN apt-get update && apt-get install --no-install-recommends -y \
    bash \
    build-essential \
    curl \
    gettext \
    git \
    libpq-dev \
    wget \
    default-libmysqlclient-dev \
    pkg-config \
 && apt-get autoremove -y && apt-get clean -y && rm -rf /var/lib/apt/lists/*

RUN pip install psycopg2-binary \
  && pip install poetry==${POETRY_VERSION} \
  && poetry --version

WORKDIR /backend

COPY pyproject.toml poetry.lock ./

RUN poetry lock
RUN poetry install --no-root

CMD ["bash", "-c", "python manage.py makemigrations && python manage.py migrate && python manage.py create_default_superuser && python manage.py create_default_staff && python manage.py runserver 0.0.0.0:8081"]