# Generated by Django 5.0.6 on 2024-06-08 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secondaryColor', models.CharField(default='#ff4000', max_length=50)),
                ('darkPrimaryColor', models.CharField(default='#f6f3eb', max_length=50)),
                ('lightPrimaryColor', models.CharField(default='#ECE6D5', max_length=50)),
                ('img_profile', models.ImageField(default='uploads/default/defaultCustomBg.jpg', null=True, upload_to='uploads/custombg/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_customizable', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
