# Generated by Django 5.0.6 on 2024-06-10 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customizeable', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customtheme',
            name='user',
        ),
    ]
