# Generated by Django 5.0.6 on 2024-06-11 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customizeable', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customtheme',
            name='user',
        ),
        migrations.AddField(
            model_name='customtheme',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customtheme',
            name='name',
            field=models.CharField(default='default', max_length=100, unique=True),
        ),
    ]
