# Generated by Django 5.0.6 on 2024-06-12 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customizeable', '0002_remove_customtheme_user_customtheme_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtheme',
            name='opacity',
            field=models.DecimalField(decimal_places=2, default=0.8, max_digits=5),
        ),
    ]
