# Generated by Django 5.0.6 on 2024-06-10 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customizeable', '0002_remove_customtheme_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtheme',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
