# Generated by Django 5.0.6 on 2024-06-10 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customizeable', '0003_customtheme_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtheme',
            name='name',
            field=models.CharField(default='Default 1', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
