# Generated by Django 5.0.6 on 2024-06-11 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customizeable', '0006_alter_customtheme_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtheme',
            name='opacity',
            field=models.IntegerField(default=0),
        ),
    ]
