# Generated by Django 5.0.6 on 2024-06-11 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customizeable', '0008_alter_customtheme_opacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customtheme',
            name='opacity',
            field=models.DecimalField(decimal_places=2, default=0.8, max_digits=5),
        ),
    ]
