# Generated by Django 5.0.6 on 2024-06-02 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bandname', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=50)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_disabled', models.BooleanField(default=False)),
                ('profile_img', models.ImageField(null=True, upload_to='uploads/band/')),
                ('banner_img', models.ImageField(null=True, upload_to='uploads/band')),
                ('modified_by', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BandMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
