# Generated by Django 5.0.6 on 2024-05-29 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bandname', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('profile_img', models.ImageField(upload_to='uploads/band/')),
                ('banner_img', models.ImageField(upload_to='uploads/band')),
            ],
        ),
    ]
