# Generated by Django 5.0.6 on 2024-06-02 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0002_band_modified_by'),
        ('user', '0011_artist_is_bandmember_alter_artist_modified_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='band',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='band',
            name='modified_by',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='BandMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.artist')),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='band.band')),
            ],
        ),
    ]
