# Generated by Django 5.0.6 on 2024-06-02 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0003_band_is_deleted_band_is_disabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='bandstagename',
            field=models.CharField(default='as', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='band',
            name='password',
            field=models.CharField(default='asdasdasdas', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
    ]
