# Generated by Django 5.0.6 on 2024-06-08 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0003_alter_band_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='banner_img',
        ),
        migrations.RemoveField(
            model_name='band',
            name='profile_img',
        ),
        migrations.AddField(
            model_name='band',
            name='img_cover',
            field=models.ImageField(default='uploads/default/cover.jpeg', null=True, upload_to='uploads/band/cover/'),
        ),
        migrations.AddField(
            model_name='band',
            name='img_profile',
            field=models.ImageField(default='uploads/default/defaultBand.png', null=True, upload_to='uploads/band/profile/'),
        ),
    ]
