# Generated by Django 5.0.6 on 2024-06-02 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0004_band_bandstagename_band_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='password',
        ),
    ]
