# Generated by Django 5.0.6 on 2024-06-02 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0005_remove_band_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='banner_img',
            field=models.ImageField(null=True, upload_to='uploads/band'),
        ),
        migrations.AlterField(
            model_name='band',
            name='profile_img',
            field=models.ImageField(null=True, upload_to='uploads/band/'),
        ),
    ]
