# Generated by Django 5.0.6 on 2024-06-02 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0006_alter_band_banner_img_alter_band_profile_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='bandstagename',
        ),
    ]
