# Generated by Django 5.0.6 on 2024-06-02 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0007_remove_band_bandstagename'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='description',
            field=models.CharField(default='asda', max_length=150),
            preserve_default=False,
        ),
    ]
