# Generated by Django 5.0.6 on 2024-05-28 17:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50, null=True)),
                ('img_banner', models.ImageField(null=True, upload_to='uploads/album/')),
                ('img_profile', models.ImageField(null=True, upload_to='uploads/album/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('release_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('totallike', models.IntegerField(default=0)),
                ('totalmusic', models.IntegerField(default=0)),
                ('is_hidden', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_released', models.BooleanField(default=False)),
                ('is_disabled', models.BooleanField(default=False)),
                ('modified_by', models.CharField(max_length=50, null=True)),
                ('artist', models.ForeignKey(default='Anonymous', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
