# Generated by Django 5.0.6 on 2024-06-02 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0003_alter_album_artist_alter_album_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='modified_by',
            field=models.IntegerField(null=True),
        ),
    ]
