# Generated by Django 5.0.6 on 2024-06-08 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0004_alter_album_modified_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='img_banner',
        ),
        migrations.AddField(
            model_name='album',
            name='img_cover',
            field=models.ImageField(default='uploads/default/cover.jpeg', null=True, upload_to='uploads/album/cover/'),
        ),
        migrations.AlterField(
            model_name='album',
            name='img_profile',
            field=models.ImageField(default='uploads/default/defaultMusic.jpg', null=True, upload_to='uploads/album/profile/'),
        ),
    ]
