# Generated by Django 5.0.6 on 2024-06-02 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0004_alter_album_modified_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='totallike',
        ),
        migrations.RemoveField(
            model_name='album',
            name='totalmusic',
        ),
        migrations.AlterField(
            model_name='album',
            name='description',
            field=models.CharField(max_length=150),
        ),
    ]
