# Generated by Django 5.0.6 on 2024-06-08 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_users_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='img_profile',
            field=models.ImageField(default='uploads/default/defaultUser.png', null=True, upload_to='uploads/user/'),
        ),
    ]
