# Generated by Django 5.0.6 on 2024-05-29 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_artist_band'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='modified_by',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
