# Generated by Django 5.0.6 on 2024-06-10 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_users_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='country',
            field=models.CharField(choices=[('Afghanistan', 'Afghanistan'), ('Armenia', 'Armenia'), ('Azerbaijan', 'Azerbaijan'), ('Bahrain', 'Bahrain'), ('Bangladesh', 'Bangladesh'), ('Bhutan', 'Bhutan'), ('Brunei', 'Brunei'), ('Cambodia', 'Cambodia'), ('China', 'China'), ('Cyprus', 'Cyprus'), ('Georgia', 'Georgia'), ('India', 'India'), ('Indonesia', 'Indonesia'), ('Iran', 'Iran'), ('Iraq', 'Iraq'), ('Israel', 'Israel'), ('Japan', 'Japan'), ('Jordan', 'Jordan'), ('Kazakhstan', 'Kazakhstan'), ('Kuwait', 'Kuwait'), ('Kyrgyzstan', 'Kyrgyzstan'), ('Laos', 'Laos'), ('Lebanon', 'Lebanon'), ('Malaysia', 'Malaysia'), ('Maldives', 'Maldives'), ('Mongolia', 'Mongolia'), ('Myanmar', 'Myanmar'), ('Nepal', 'Nepal'), ('Oman', 'Oman'), ('Pakistan', 'Pakistan'), ('Palestine', 'Palestine'), ('Philippines', 'Philippines'), ('Qatar', 'Qatar'), ('Saudi Arabia', 'Saudi Arabia'), ('Singapore', 'Singapore'), ('South Korea', 'South Korea'), ('Sri Lanka', 'Sri Lanka'), ('Syria', 'Syria'), ('Taiwan', 'Taiwan'), ('Tajikistan', 'Tajikistan'), ('Thailand', 'Thailand'), ('Timor-Leste', 'Timor-Leste'), ('Turkey', 'Turkey'), ('Turkmenistan', 'Turkmenistan'), ('United Arab Emirates', 'United Arab Emirates'), ('Uzbekistan', 'Uzbekistan'), ('Vietnam', 'Vietnam'), ('Yemen', 'Yemen')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='img_cover',
            field=models.ImageField(default='uploads/default/cover.jpeg', null=True, upload_to='uploads/user/cover/'),
        ),
        migrations.AlterField(
            model_name='users',
            name='img_profile',
            field=models.ImageField(default='uploads/default/defaultUser.jpg', null=True, upload_to='uploads/user/profile/'),
        ),
    ]
