# Generated by Django 5.0.6 on 2024-05-29 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_artist_modified_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='bio',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Male'), (1, 'Female'), (2, 'Others')], default=0),
        ),
    ]
