# Generated by Django 5.0.6 on 2024-06-08 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_users_img_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='img_cover',
            field=models.ImageField(default='uploads/default/cover.jpeg', null=True, upload_to='uploads/user/cover/'),
        ),
        migrations.AlterField(
            model_name='users',
            name='img_profile',
            field=models.ImageField(default='uploads/default/defaultUser.jpg', null=True, upload_to='uploads/user/profile/'),
        ),
    ]
