# Generated by Django 5.0.6 on 2024-06-11 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customizeable', '0002_remove_customtheme_user_customtheme_is_deleted_and_more'),
        ('user', '0003_alter_users_country_alter_users_img_cover_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='theme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customizeable.customtheme'),
        ),
    ]
