# Generated by Django 5.0.6 on 2024-05-30 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_users_bio_alter_users_gender_and_more'),
        ('user', '0005_users_created_at_users_created_by_and_more'),
    ]

    operations = [
    ]
