# Generated by Django 5.0.6 on 2024-06-10 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customizeable', '0006_alter_customtheme_name'),
        ('user', '0005_alter_users_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='theme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customizeable.customtheme'),
        ),
    ]
