# Generated by Django 5.0.6 on 2024-05-30 10:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_users_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='created_at',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
