# Generated by Django 5.0.6 on 2024-06-01 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_users_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='band',
        ),
    ]
