# Generated by Django 5.0.6 on 2024-06-01 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_users_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='band',
        ),
    ]
