# Generated by Django 5.0.6 on 2024-06-02 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_remove_artist_band'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='is_bandMember',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='artist',
            name='modified_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='stagename',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
