# Generated by Django 5.0.6 on 2024-06-02 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_artist_is_bandmember_alter_artist_modified_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='bio',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
