# Generated by Django 5.0.6 on 2024-06-02 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0009_alter_bandmember_artist'),
        ('user', '0012_alter_users_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='img_cover',
            field=models.ImageField(null=True, upload_to='uploads/user/'),
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
    ]
