# Generated by Django 5.0.6 on 2024-06-09 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genre', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='weather',
            field=models.CharField(choices=[('Clear', 'Clear'), ('Clouds', 'Clouds'), ('Rain', 'Rain'), ('Drizzle', 'Drizzle'), ('Thunderstorm', 'Thunderstorm'), ('Snow', 'Snow'), ('Mist', 'Mist'), ('Smoke', 'Smoke'), ('Haze', 'Haze'), ('Dust', 'Dust'), ('Fog', 'Fog'), ('Sand', 'Sand'), ('Ash', 'Ash'), ('Squall', 'Squall'), ('Tornado', 'Tornado')], max_length=20, null=True),
        ),
    ]
